name: "Testing"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cache TFLint plugins
        uses: actions/cache@v3
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ hashFiles('.tflint.hcl') }} 
      - name: Cache Terraform plugins
        uses: actions/cache@v3
        with:
          path: "**/.terraform"
          key: terraform-${{ hashFiles('.terraform.lock.hcl') }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v3
      - name: Run lint
        run: make lint
